name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install google-cloud-speech

- name: Transcribe Audio
  run: |
    export GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
    python script.py
