name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python script.py

    - name: Save results
      run: |
        mkdir -p results
        cp output.txt results/
        git add results
        git commit -m "Automated: Save results"
