name: Transcribe Audio

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Transcribe Audio
      run: python script.py transcribe_all
